// components/dashboard/dashboard-layout.tsx
"use client"

import type React from "react"

import { useState } from "react"
import { DashboardSidebar } from "./dashboard-sidebar"
import { DashboardNavbar } from "./dashboard-navbar"

interface DashboardLayoutProps {
  children: React.ReactNode
}

export function DashboardLayout({ children }: DashboardLayoutProps) {
  const [sidebarOpen, setSidebarOpen] = useState(false)

  return (
    <div className="min-h-screen bg-background">
      <DashboardSidebar isOpen={sidebarOpen} onClose={() => setSidebarOpen(false)} />

      <div className="lg:pl-64">
        <DashboardNavbar onMenuClick={() => setSidebarOpen(true)} />

        <main className="p-4 lg:p-8">
          <div className="max-w-7xl mx-auto">{children}</div>
        </main>
      </div>
    </div>
  )
}

// components/dashboard/dashboard-layout.vue
<template>
  <div class="min-h-screen bg-light">
    <dashboard-navbar />
    <div class="container-fluid">
      <div class="row">
        <dashboard-sidebar />
        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4 py-4">
          <slot></slot>
        </main>
      </div>
    </div>
  </div>
</template>

<script>
import DashboardNavbar from './dashboard-navbar.vue'
import DashboardSidebar from './dashboard-sidebar.vue'

export default {
  name: 'DashboardLayout',
  components: {
    DashboardNavbar,
    DashboardSidebar
  }
}
</script>

<style scoped>
.bg-light {
  background-color: #f8f9fa;
}
</style>
