// components/dashboard/dashboard-layout.jsx
import React from 'react'
import { DashboardNavbar } from './dashboard-navbar'
import { DashboardSidebar } from './dashboard-sidebar'

export function DashboardLayout({ children }) {
  return (
    <div className="min-h-screen bg-gray-100">
      <DashboardNavbar />
      <div className="flex">
        <DashboardSidebar />
        <main className="flex-1 p-6">
          {children}
        </main>
      </div>
    </div>
  )
}

// components/dashboard/dashboard-layout.vue
<template>
  <div class="min-h-screen bg-light">
    <dashboard-navbar />
    <div class="container-fluid">
      <div class="row">
        <dashboard-sidebar />
        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4 py-4">
          <slot></slot>
        </main>
      </div>
    </div>
  </div>
</template>

<script>
import DashboardNavbar from './dashboard-navbar.vue'
import DashboardSidebar from './dashboard-sidebar.vue'

export default {
  name: 'DashboardLayout',
  components: {
    DashboardNavbar,
    DashboardSidebar
  }
}
</script>

<style scoped>
.bg-light {
  background-color: #f8f9fa;
}
</style>
